version: 2.1

commands:
  install-commit-install:
    steps:
      - run: npm install @cypress/commit-message-install@2.5.2

  install-and-test:
    description: Installs necessary Cypress version and verifies it.
    steps:
      - checkout
      - run: npm install
      - install-commit-install
      - run: $(npm bin)/commit-message-install --else "npm install cypress"
      - run: $(npm bin)/run-if $(npm bin)/cypress version
      - run: DEBUG=cypress:cli $(npm bin)/run-if $(npm bin)/cypress verify
      - run: $(npm bin)/run-if $(npm bin)/cypress info
      - run: $(npm bin)/run-if $(npm bin)/cypress cache list
      - run: $(npm bin)/run-if $(npm bin)/cypress cache list --size

  send-status:
    description: Send failed status right away
    steps:
      - run:
          when: on_fail
          name: Set status check
          command: $(npm bin)/set-status --state failure --description "$CIRCLE_STAGE on CircleCI"

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  environment:
    - npm_config_engine_strict: 1

jobs:
  "node-12-0-0":
    <<: *defaults
    docker:
      - image: cypress/base:12.0.0
        user: node
    steps:
      - install-and-test
      - send-status

  "node-12-npm-ci":
    <<: *defaults
    docker:
      - image: cypress/base:12.0.0
        user: node
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run: npm init -y
      - run: time npm ci
      - install-commit-install
      - run: npm t
      - run: $(npm bin)/commit-message-install --else "npm i cypress"
      - run: $(npm bin)/run-if $(npm bin)/cypress version
      - run: DEBUG=cypress:cli $(npm bin)/run-if $(npm bin)/cypress verify
      - send-status

  "node-12":
    <<: *defaults
    docker:
      - image: cypress/base:12.0.0
        user: node
    steps:
      - install-and-test
      - send-status

  "node-14":
    <<: *defaults
    docker:
      - image: cypress/base:14.15.4
        user: node
    steps:
      - install-and-test
      - send-status

  "chrome-browser-77":
    # really old version of Chrome, should not be supported in v3.5.0
    <<: *defaults
    docker:
      - image: cypress/browsers:node12.6.0-chrome77
    steps:
      - checkout
      - install-commit-install
      - run: git clone https://github.com/cypress-io/cypress-test-tiny.git
      - run:
          working_directory: cypress-test-tiny
          command: npm install
      - run:
          working_directory: cypress-test-tiny
          command: npm install @cypress/commit-message-install@2.5.2
      # because cypress-test-tiny no longer installs Cypress
      # we need to install one
      - run:
          working_directory: cypress-test-tiny
          command: npm install cypress
      - run:
          working_directory: cypress-test-tiny
          command: $(npm bin)/commit-message-install
      - run:
          name: Test using Chrome
          command: $(npm bin)/run-if $(npm bin)/cypress run --browser chrome
          working_directory: cypress-test-tiny
      - send-status

  after-tests:
    # a job that sets success commit status
    # after all test jobs finish successfully
    <<: *defaults
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      # TODO cache dependencies to avoid reinstalling Cypress
      - install-commit-install
      - run:
          when: on_success
          name: Set status check
          command: $(npm bin)/set-status --state success --description "on CircleCI"

workflows:
  version: 2
  test-cypress-installs:
    jobs:
      - node-12-0-0:
          context: test-runner:commit-status-checks
      - node-12-npm-ci:
          context: test-runner:commit-status-checks
      - node-12:
          context: test-runner:commit-status-checks
      - node-14:
          context: test-runner:commit-status-checks
      - chrome-browser-77:
          context: test-runner:commit-status-checks

      - after-tests:
          context: test-runner:commit-status-checks
          requires:
            - node-12-0-0
            - node-12-npm-ci
            - node-12
            - node-14
            - chrome-browser-77
